Feature1
oceaneLonneux/GameSparta pull request #1
Opened 2018-08-14 17:24 UTC by oceaneLonneux

It is done at 90%. I just need to get the timer right, but the main work is done!

2018-08-14 18:13 UTC, AEJackson requested changes

2018-08-14 18:13 UTC, AEJackson commented on artwork/artwork.html
> +<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="an
check indentation

2018-08-14 18:13 UTC, AEJackson commented on Play/play.html
> +  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="
have you included bootstrap.min.css 2 times?

2018-08-14 18:13 UTC, AEJackson commented on index.html
> +  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
your JS file should come after JQuery's & bootstrap's
also indent you jQuery and bootstrap script tags

2018-08-14 21:20 UTC, oceaneLonneux commented
Did the changes of indentation you requested

2018-08-14 22:30 UTC, richgurney requested changes

2018-08-14 22:30 UTC, richgurney commented on Play/play.js
> +// make an array of [0 1 2]
No commented out code

2018-08-15 07:48 UTC, oceaneLonneux commented
Took off the commented code in play.js

2018-08-15 09:51 UTC, AEJackson requested changes

2018-08-15 09:51 UTC, AEJackson commented on index.html
> +    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
index.js script tag is no longer included is this an oversight ?

2018-08-15 09:53 UTC, oceaneLonneux commented
I am not using JS with my index.html, therefore why I don't have a script for that anymore.

2018-08-15 09:57 UTC, AEJackson requested changes

2018-08-15 09:57 UTC, AEJackson commented on artwork/artwork.html
> +    </script>
orphan </script> tag (is has no opening tag associated with it)

2018-08-15 09:57 UTC, AEJackson commented on index.html
> +                    </div>
check indentation

2018-08-15 21:23 UTC, oceaneLonneux commented
Did the changes requested. The game is working, I just need to work a bit more on LocalStorage but I almost understand the logic of it!

2018-08-15 21:36 UTC, richgurney requested changes

2018-08-15 21:36 UTC, richgurney commented on Play/play.js
> +      }) //record the score
Commented out code here

2018-08-15 21:36 UTC, richgurney commented on Play/play.js
> +      // console.log(timeLeft);
Comments Here too?

2018-08-15 21:36 UTC, richgurney commented on index.html
> +                          <div class="modal-body">
Can you fix the indentation here please

2018-08-16 11:03 UTC, oceaneLonneux commented
started working on the game for players 2!

2018-08-16 11:05 UTC, AEJackson requested changes

2018-08-16 11:05 UTC, AEJackson commented on Play/play.html
>      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin
you have include the bootstrap css file but not it's js file

2018-08-16 11:05 UTC, AEJackson commented on index.html
> +                        <div class="modal-body">
why is this indented
check indentation.

2018-08-17 11:31 UTC, AEJackson submitted a review, later dismissed

2018-08-17 11:31 UTC, AEJackson commented on Play/play.js
> +     if (localStorage.getItem(1)>localStorage.getItem(2)) {
check indentation

2018-08-17 11:31 UTC, AEJackson commented on Play/play.js
> +       }
check indentation

2018-08-17 11:31 UTC, AEJackson commented on Play/play.js
>          $(".img img:last-child").remove() //i want the last monster to disappear
check indentation

2018-08-17 11:31 UTC, AEJackson commented on Play/play.js
>      })//end enemy click function
check indentation

2018-08-17 11:31 UTC, AEJackson commented on Play/play.js
> +      score.html("<b  class='playerscore1'> Score: " + playerScore1 + " </b>");
check indentation

2018-08-17 11:31 UTC, AEJackson commented on Play/play.js
>        }
check indentation

2018-08-17 11:31 UTC, AEJackson commented on Play/play.js
> +      })
check indentation

2018-08-17 11:31 UTC, AEJackson commented on artwork/artwork.css
> +/*
remove commented out code

2018-08-19 12:57 UTC, richgurney approved these changes

2018-08-19 16:52 UTC, richgurney approved these changes

2018-08-19 16:52 UTC, merged